# Generated by Django 2.2.1 on 2019-09-14 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0002_auto_20190914_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('media', models.ImageField(upload_to='media/')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 9, 14, 20, 39, 47, 881818, tzinfo=utc))),
                ('status', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'Not Accepted')], default='N', max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='complaints_app.Department')),
                ('grievant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='complaints_app.Grievant')),
            ],
            options={
                'verbose_name_plural': 'Complaints',
            },
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
