# Generated by Django 2.2.1 on 2019-09-14 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0003_auto_20190914_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievant',
            name='Registeration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 20, 42, 44, 290605, tzinfo=utc)),
        ),
    ]
