# Generated by Django 2.2.1 on 2019-09-14 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0004_auto_20190914_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 20, 43, 34, 942740, tzinfo=utc)),
        ),
    ]
