# Generated by Django 2.2.1 on 2019-09-14 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0007_auto_20190914_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 20, 51, 39, 458006, tzinfo=utc)),
        ),
    ]
