# Generated by Django 2.2.1 on 2019-09-14 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0008_auto_20190914_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 20, 52, 36, 647257, tzinfo=utc)),
        ),
    ]
