# Generated by Django 2.2.1 on 2019-09-14 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0010_auto_20190914_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Heading',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 21, 9, 9, 637233, tzinfo=utc)),
        ),
    ]
