# Generated by Django 2.2.1 on 2019-09-14 21:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0014_auto_20190914_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='Heading',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 21, 13, 22, 874388, tzinfo=utc)),
        ),
    ]
