# Generated by Django 2.2.1 on 2019-09-14 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0017_auto_20190914_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 21, 17, 55, 66991, tzinfo=utc)),
        ),
    ]
