# Generated by Django 2.2.1 on 2019-09-15 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0019_auto_20190915_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievant',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 2, 0, 8, 796516, tzinfo=utc)),
        ),
    ]
