# Generated by Django 2.2.1 on 2019-09-15 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0020_auto_20190915_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 2, 7, 45, 187905, tzinfo=utc)),
        ),
    ]
